![](https://drive.google.com/uc?export=view&id=1vv_PsWBnUJwSCkwKDoJAC-vXjtaEA4Ts)

# Introduction to Pandas

### What is Pandas?
As Python has grown to become a popular solution for data analysis, many new tools have been introduced to support such tasks. Pandas is arguably the most popular and widely used of these, although it does have some limitations (if working with very large datasets you may want to look at Dask and/or PySpark).

First, we will import it into our session. We will also import numpy - another widely used Python package for working with numerical data (the name is a portmanteau of "numerical" and "python"). By convention we import pandas as "pd" and numpy as "np". This is equivalent to giving it a variable name.

In [ ]:
import pandas as pd
import numpy as np

### Testing our installation
To test everything is working we will create some fake data frame using numpy and load it into a pandas dataframe (more on these below). First we will create the random numbers:

notes: random.rand(# of digits, up to this number) so like 10 decimals between 0 to 1

In [ ]:
x = np.random.rand(10,1)
x

array([[0.85548011],
       [0.74465229],
       [0.97788516],
       [0.59995625],
       [0.03227438],
       [0.61243426],
       [0.94898071],
       [0.40475119],
       [0.22031344],
       [0.08738039]])

The commands here have told numpy to create a set of random numbers between zero and one. The arguments we have passed, "1" and "10", tells numpy we want a 10x1 array of numbers (i.e. a vector).

Next we will create a pandas dataframe using "x":

In [ ]:
testdf = pd.DataFrame(x)
testdf

          0
0  0.855480
1  0.744652
2  0.977885
3  0.599956
4  0.032274
5  0.612434
6  0.948981
7  0.404751
8  0.220313
9  0.087380

We have now successfully created a pandas dataframe!

### What are Dataframes?
Pandas has a very elegant way of managing data, very much borrowed from the statistical language R, mostly based around dataframes. You can think of dataframes a bit like an Excel table with rows, columns and common operations like sum, average and so on. We can use this on top of our previous work on lists and dictionaries (etc.) more usable and malleable.

To begin with we will create a dataset - in this case a dictionary.

In [ ]:
orders = {'o10001':{'date':'2025/01/10', 'product':'Blockchain database', 'quantity':'1'},
            'o10002':{'date':'2025/01/13', 'product':'Stock market prediction engine', 'quantity':'2'},
            'o10003':{'date':'2025/01/14', 'product':'Portfolio optimisation tool', 'quantity':'10'},
            'o10004':{'date':'2025/01/15', 'product':'Man\'s suit', 'quantity':'2'}
}
orders

{'o10001': {'date': '2025/01/10',
  'product': 'Blockchain database',
  'quantity': '1'},
 'o10002': {'date': '2025/01/13',
  'product': 'Stock market prediction engine',
  'quantity': '2'},
 'o10003': {'date': '2025/01/14',
  'product': 'Portfolio optimisation tool',
  'quantity': '10'},
 'o10004': {'date': '2025/01/15', 'product': "Man's suit", 'quantity': '2'}}

We can convert this to a Dataframe with great ease

In [ ]:
import pandas as pd
import numpy as np

orders_df = pd.DataFrame(orders)
orders_df

,o10001,o10002,o10003,o10004
date,2025/01/10,2025/01/13,2025/01/14,2025/01/15
product,Blockchain database,Stock market prediction engine,Portfolio optimisation tool,Man's suit
quantity,1,2,10,2

We can even create such outputs from more complex dictionaries, such as a dictionary which includes a nested list:

In [ ]:
customers = {'Siamak':{'name':'Siamak Naderi', 'open_orders':3, 'orders':['o10001', 'o10002', 'o10004']},
             'Ram':{'name':'Ram Gopal', 'open_orders':0, 'orders':[]},
             'Moris':{'name':'Moris Strub', 'open_orders':1, 'orders':['o10003']},
             'Ephie':{'name':'Ephie Wang', 'open_orders':0, 'orders':[]}
}
customers

{'Siamak': {'name': 'Siamak Naderi',
  'open_orders': 3,
  'orders': ['o10001', 'o10002', 'o10004']},
 'Ram': {'name': 'Ram Gopal', 'open_orders': 0, 'orders': []},
 'Moris': {'name': 'Moris Strub', 'open_orders': 1, 'orders': ['o10003']},
 'Ephie': {'name': 'Ephie Wang', 'open_orders': 0, 'orders': []}}

In [ ]:
customers_df = pd.DataFrame(customers)
customers_df

                               Siamak        Ram        Moris       Ephie
name                    Siamak Naderi  Ram Gopal  Moris Strub  Ephie Wang
open_orders                         3          0            1           0
orders       [o10001, o10002, o10004]         []     [o10003]          []

Pandas dataframes can also be built from various other data structures and sources (including Excel files, CSVs, text files, databases and many more). To conclude the session we will look at a list example:

In [ ]:
a = [1, 2, 3, 4]
b = ["a", "b", "c", "d"]
c = [True, False, True, False]

listdf = pd.DataFrame([a, b, c])
listdf

      0      1     2      3
0     1      2     3      4
1     a      b     c      d
2  True  False  True  False

### EXERCISE
Try building you own dataframes from a list and/or dictionary you create. What would happen if you have an item missing from one element. E.g. if "c" in the above example only had three items - True, False, True - rather than four. Test it - does the output match your expectation?

In [20]:
lessons = {'001':{'month':'11', 'Number of Student':'3', 'quantity':'3'},
            '002':{'month':'12', 'Number of Student':'4', 'quantity':'2'},
            '003':{'month':'8', 'Number of Student':'8', 'quantity':'8'},
            '004':{'month':'9', 'Number of Student': '8', 'quantity':'10'}
}
orders

{'o10001': {'date': '2025/01/10',
  'product': 'Blockchain database',
  'quantity': '1'},
 'o10002': {'date': '2025/01/13',
  'product': 'Stock market prediction engine',
  'quantity': '2'},
 'o10003': {'date': '2025/01/14',
  'product': 'Portfolio optimisation tool',
  'quantity': '10'},
 'o10004': {'date': '2025/01/15', 'product': "Man's suit", 'quantity': '2'}}

In [18]:
import pandas as pd
import numpy as np

lessons_df = pd.DataFrame(lessons)
lessons_df

                  001 002 003  004
month              11  12   8    9
Number of Student   3   4   8  NaN
quantity            3   2   8   10

The output sort of matches what i would have thought. Although I thought maybe the code wouldnt run at all but if it did it would show NaN. Playing around with it this is what i have observed.

if it is missing an entire item like so : 003 number of student

lessons = {'001':{'month':'11', 'Number of Student':'3', 'quantity':'3'},
            '002':{'month':'12', 'Number of Student':'4', 'quantity':'2'},
            '003':{'month':'8',  ---- , 'quantity':'8'},
            '004':{'month':'9', 'Number of Student': '8', 'quantity':'10'}
}
orders

the code still runs but shows NaN for the 4th item of the list.

but if it is missing the second component within an item liek so : 003 number of student '8'

lessons = {'001':{'month':'11', 'Number of Student':'3', 'quantity':'3'},
            '002':{'month':'12', 'Number of Student':'4', 'quantity':'2'},
            '003':{'month':'8', 'Number of Student': --- , 'quantity':'8'},
            '004':{'month':'9', 'Number of Student': '8', 'quantity':'10'}
}
orders

the code will not run.

import pandas as pd
import numpy as np
lessons_df = pd.DataFrame(lessons)
lessons_df